server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
#      defaultZone: http://eureka7003:7001/eureka/,http://eureka7004:7002/eureka/  #集群版
      defaultZone: http://eureka7003:7001/eureka/ #单机版配置
  instance:
    lease-expiration-duration-in-seconds: 2 #eurake服务端在收到最后一次心跳后的等待时间上限，单位为秒（默认是90秒），超时讲剔除
    lease-renewal-interval-in-seconds: 1  #eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）

spring:
  application:
    name: cloud-consumer-order
